### ISSUE TITLE
Can not see the code file code.py

### ISSUE THREAD

**Issue by ralgond** [intellygenta/KDDCup2021#2]
Hi, genta

In this repository, only I can see is the readme.md. And I can not see the code file "code.py" which is referred in the readme.md.

**Comment by intellygenta** [comment]
Hi, Teng

Sorry for the late reply.
I have uploaded the code file "code.py" and the result file "result.csv".
Thank you for your interest.

**Comment by ralgond** [comment]
Now I can see it, Thank you!
